/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/2S4LROwI9Ua
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Checkbox } from "@/components/ui/checkbox"


export default function giftagcomp() {
  return (
    <div className="max-w-lg mx-auto p-4 space-y-6">
      <div className="space-y-2">
        <h2 className="text-xl font-bold">Step 1</h2>
        <h1 className="text-3xl font-bold text-center">Amount & Message</h1>
        <hr className="border-t-2 border-yellow-500" />
      </div>
      <div className="flex items-center space-x-2">
        <Input type="text" placeholder="Custom amount Min $10 - Max $100" className="flex-1 border border-blue-500" />
        <Button className="bg-blue-500 text-white">Apply</Button>
      </div>
      <Input type="email" placeholder="Your Email" className="w-full" />
      <Input type="text" placeholder="Your Name" className="w-full" />
      <Input type="email" placeholder="Recipient Email" className="w-full" />
      <div className="space-y-2">
        <div className="flex items-center space-x-2">
          <Checkbox id="updates" />
          <label htmlFor="updates" className="text-sm">
            Send me updates on this giftag
          </label>
        </div>
        <div className="flex items-center space-x-2">
          <Checkbox id="marketing" />
          <label htmlFor="marketing" className="text-sm">
            Send me marketing updates
          </label>
        </div>
      </div>
      <div className="space-y-2 text-center">
        <a href="#" className="text-blue-500 underline text-lg">
          Preview the experience
        </a>
        <iframe width="100%" height="315" src="https://www.youtube.com/embed/a-j6xNluy1Q?si=zFBR5BCMOyPAvXQH" title="YouTube video player" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" ></iframe>
     
      </div>
      <div className="flex justify-between">
        <Button className="bg-gray-200 text-gray-700 flex items-center">
          <ChevronLeftIcon className="mr-2" />
          Back
        </Button>
        <Button className="bg-yellow-500 text-black flex items-center">
          Confirm
          <ChevronRightIcon className="ml-2" />
        </Button>
      </div>
    </div>
  )
}


function ChevronLeftIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m15 18-6-6 6-6" />
    </svg>
  )
}




function ChevronRightIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  )
}
